name: Deploy to Nominalia via FTP

on:
  push:
    branches:
      - main   # Se deploya cada vez que subes a main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: FTP Deploy to Nominalia
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}

        # Carpeta de tu proyecto en GitHub
        local-dir: .

        # Carpeta p√∫blica en Nominalia
        server-dir: /www

        # NO borrar todo para evitar problemas
        dangerous-clean-slate: false
